---
grid: 5
tech: sky130A
gamma: 1.3
beta: 1.54
units: Nano
layers:
  m2:
    desc: second level of metal interconnects
    width: 140
    space: 140
    area: 67600
    enclosures: []
    extensions: []
    layernum: 69
    purposes:
      - - Drawing
        - 20
      - - Pin
        - 16
      - - Label
        - 5
  via:
    desc: defines contacts between metal 1 and metal 2
    width: 150
    space: 170
    area: 67600
    enclosures:
      - layer: m1
        enclosure: 55
        one_side: false
      - layer: m1
        enclosure: 85
        one_side: true
      - layer: m2
        enclosure: 55
        one_side: false
      - layer: m2
        enclosure: 85
        one_side: true
    extensions: []
    layernum: 68
    purposes:
      - - Drawing
        - 44
  npc:
    desc: define nitride poly cuts under licon1 areas
    width: 270
    space: 270
    area: 1
    enclosures: []
    extensions: []
    layernum: 95
    purposes:
      - - Drawing
        - 20
  psdm:
    desc: define p+ source/drain implants
    width: 380
    space: 380
    area: 255000
    enclosures: []
    extensions: []
    layernum: 94
    purposes:
      - - Drawing
        - 20
  via2:
    desc: defines contacts between metal 2 and metal 3
    width: 200
    space: 200
    area: 67600
    enclosures:
      - layer: m2
        enclosure: 40
        one_side: false
      - layer: m2
        enclosure: 85
        one_side: true
      - layer: m3
        enclosure: 65
        one_side: false
    extensions: []
    layernum: 69
    purposes:
      - - Drawing
        - 44
  ntap:
    desc: define n+ taps to nwell
    width: 150
    space: 270
    area: 0
    enclosures:
      - layer: nwell
        enclosure: 180
        one_side: false
    extensions: []
    layernum: 65
    purposes:
      - - Drawing
        - 44
  li:
    desc: local interconnect
    width: 170
    space: 170
    area: 56100
    enclosures: []
    extensions: []
    layernum: 67
    purposes:
      - - Drawing
        - 20
      - - Label
        - 5
  nwell:
    desc: define nwell for placing PMOS transistors
    width: 840
    space: 1270
    area: 0
    enclosures: []
    extensions: []
    layernum: 64
    purposes:
      - - Drawing
        - 20
      - - Label
        - 5
      - - Pin
        - 16
  dnwell:
    desc: define dnwell region
    width: 840
    space: 1270
    area: 0
    enclosures: []
    extensions: []
    layernum: 64
    purposes:
      - - Drawing
        - 18
  m3:
    desc: third level of metal interconnects
    width: 300
    space: 300
    area: 240000
    enclosures: []
    extensions: []
    layernum: 70
    purposes:
      - - Drawing
        - 20
      - - Pin
        - 16
      - - Label
        - 5
  licon:
    desc: defines contacts between poly/diff/tap and local interconnect
    width: 170
    space: 170
    area: 28900
    enclosures:
      - layer: diff
        enclosure: 40
        one_side: false
      - layer: diff
        enclosure: 60
        one_side: true
      - layer: poly
        enclosure: 50
        one_side: false
      - layer: poly
        enclosure: 80
        one_side: true
      - layer: li
        enclosure: 80
        one_side: true
      - layer: ntap
        enclosure: 120
        one_side: true
      - layer: ntap
        enclosure: 40
        one_side: false
      - layer: ptap
        enclosure: 120
        one_side: true
      - layer: ptap
        enclosure: 40
        one_side: false
      - layer: npc
        enclosure: 100
        one_side: false
    extensions: []
    layernum: 66
    purposes:
      - - Drawing
        - 44
  diff:
    desc: nmos/pmos diffusion regions
    width: 150
    space: 270
    area: 63000
    enclosures:
      - layer: nwell
        enclosure: 180
        one_side: false
      - layer: nsdm
        enclosure: 125
        one_side: false
      - layer: psdm
        enclosure: 125
        one_side: false
    extensions:
      - layer: poly
        extend: 250
    layernum: 65
    purposes:
      - - Drawing
        - 20
      - - Label
        - 6
  ptap:
    desc: define p+ taps to substrate
    width: 150
    space: 270
    area: 0
    enclosures:
      - layer: pwell
        enclosure: 130
        one_side: false
    extensions: []
    layernum: 65
    purposes:
      - - Drawing
        - 44
  mcon:
    desc: contact between li and m1
    width: 170
    space: 190
    area: 28900
    enclosures:
      - layer: m1
        enclosure: 30
        one_side: false
      - layer: m1
        enclosure: 60
        one_side: true
    extensions: []
    layernum: 67
    purposes:
      - - Drawing
        - 44
  m1:
    desc: first level of metal interconnects
    width: 140
    space: 140
    area: 83000
    enclosures: []
    extensions: []
    layernum: 68
    purposes:
      - - Drawing
        - 20
      - - Label
        - 5
      - - Pin
        - 16
  nsdm:
    desc: define n+ source/drain implants
    width: 380
    space: 380
    area: 265000
    enclosures: []
    extensions: []
    layernum: 93
    purposes:
      - - Drawing
        - 44
  poly:
    desc: define transistor gates
    width: 150
    space: 210
    area: 0
    enclosures: []
    extensions:
      - layer: diff
        extend: 130
      - layer: diff
        extend: 130
    layernum: 66
    purposes:
      - - Drawing
        - 20
      - - Label
        - 5
      - - Pin
        - 16
      - - Named:
          - text
          - 83
        - 83
      - - Named:
          - net
          - 23
        - 23
  cp1m:
    desc: empty
    layernum: 33
    purposes:
      - - Named:
          - add
          - 43
        - 43
  prBndry:
    desc: empty
    layernum: 235
    purposes:
      - - Named:
          - boundary
          - 4
        - 4
  cfom:
    desc: empty
    layernum: 22
    purposes:
      - - Named:
          - add
          - 21
        - 21
      - - Named:
          - drop
          - 22
        - 22
  hvtp:
    desc: define high-Vt pmos implants
    layernum: 78
    purposes:
      - - Drawing
        - 44
  id_sram:
    desc: define memory core cells
    layernum: 81
    purposes:
      - - Drawing
        - 2
  id_sc:
    desc: define standard cells
    layernum: 81
    purposes:
      - - Drawing
        - 4
  ncm:
    desc: define N-core implant
    layernum: 92
    purposes:
      - - Drawing
        - 44
  cli1m:
    desc: empty
    layernum: 115
    purposes:
      - - Drawing
        - 44
      - - Named:
          - add
          - 43
        - 43
      - - Named:
          - drop
          - 42
        - 42
  pwell:
    desc: empty
    layernum: 64
    purposes:
      - - Label
        - 59
  pwellpin:
    desc: empty
    layernum: 122
    purposes:
      - - Pin
        - 16

spacing:
  - from: diff
    to: nwell
    dist: 340
  - from: gate
    to: licon
    dist: 55
  - from: gate
    to: npc
    dist: 90
  - from: licon
    to: diff
    dist: 235
  - from: nsdm
    to: diff
    dist: 130
  - from: psdm
    to: diff
    dist: 130
stacks:
  ntap:
    layers:
      - li
      - licon
      - ntap
  ndiffc:
    layers:
      - li
      - licon
      - diff
  via2:
    layers:
      - m3
      - via2
      - m2
  viali:
    layers:
      - m1
      - mcon
      - li
  via1:
    layers:
      - m2
      - via
      - m1
  polyc:
    layers:
      - li
      - licon
      - poly
  pdiffc:
    layers:
      - li
      - licon
      - diff
