[package]
name = "magic_vlsi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
log = "0.4"

[dev-dependencies]
lazy_static = "1.4.0"
