[package]
name = "micro_hdl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
micro_hdl_derive = { path = "./micro_hdl_derive" }

[dev-dependencies]
tempfile = "3.3"
